### ISSUE TITLE
API for subrouting

### ISSUE THREAD

**Issue by Kelin2025** [atomic-router/atomic-router#13]
Sometimes we have some "parent" page with subpages. 
E.g. user page where you can see user posts (`/my/posts`) or info (`/my/info`)
Would be cool to have something like this:
```tsx
const router = createHistoryRouter({
  { 
    path: '/my',
    route: myRoute,
    children: [
      { path: '/posts', route: myPostsRoute },
      { path: '/info', route: myInfoRoute }
    ]
  }
})
```
Which would work almost the same way as 

```tsx
const router = createHistoryRouter({
  { path: '/my/(posts|info)*', route: myRoute },
  { path: '/my/posts', route: myPostsRoute },
  { path: '/my/info', route: myInfoRoute }
})
```

**Comment by sergeysova** [comment]
What you will do in this way?

```ts
const router = createHistoryRouter({
  { 
    path: '/my/:name',
    route: myRoute,
    children: [
      { path: '/posts/:postId', route: myPostsRoute },
    ]
  }
})
```

1. I on the `/my/sova/post/1` route
2. How can I redirect to a `/my/sova/post/2` ?
3. What about redirect from (1) to `/my/another/post/3` ?

**Comment by Kelin2025** [comment]
Won't be implemented due to the problem described above
However, if you need to add just a path prefix without params, there's now a `base` param in `createHistoryRouter`
https://github.com/atomic-router/atomic-router/releases/tag/v0.5.0
