### ISSUE TITLE
routeNotFound event does not fire

### ISSUE THREAD

**Issue by Drevoed** [atomic-router/atomic-router#47]
Starting from v0.7.0 - routeNotFound does not fire anymore when routes were not found. 

repro: https://stackblitz.com/edit/react-29q7nu?file=src%2Fapp%2Findex.tsx

click "non-existing page"

expected:
404 page opened

actual:
blank page

**Comment by Kelin2025** [comment]
Works perfectly fine, [see here](https://stackblitz.com/edit/react-hdskny?file=src/app/routing.tsx)

Please, make sure that you subscribe to `routeNotFound` **before** `router.setHistory` is triggered. Otherwise, it won't be triggered on startup
